FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=secret
ENV MYSQL_DATABASE=mysql_db
ENV MYSQL_USER=db_user
ENV MYSQL_PASSWORD=secret
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

RUN apt-get update && apt-get install -y \
    nano
